import type { Mentor, Review } from '../Find_Mentor/mentorr'

export const skillFilters = [
  'All', 'AWS', 'Docker', 'FastAPI', 'Kubernetes', 'MongoDB',
  'Next.js', 'Node.js', 'PostgreSQL', 'Python', 'React', 'SQL',
  'System design', 'TypeScript', 'dbt',
]

export const mentors: Mentor[] = [
  {
    id: 1,
    name: 'Ava Chen',
    initials: 'AC',
    title: 'Senior React engineer @ Vercel',
    rating: 5.0,
    reviewCount: 4,
    hourlyRate: 60,
    available: true,
    skills: ['React', 'TypeScript', 'Next.js'],
    nextAvailable: [
      { time: '02:00 PM', available: true },
      { time: '04:00 PM', available: true },
      { time: '09:00 AM', available: true },
    ],
    location: 'Remote · Worldwide',
    language: 'English (Native)',
    responseTime: 'Responds within 2h',
    bio: '8 years shipping production React apps. Loves teaching hooks, rendering, and Suspense.',
    aiSummary:
      'Ava is praised for react, clear explanations, and hands-on guidance. Learners value the practical approach across React and TypeScript. Some note occasional scheduling delays.',
    scores: { responseTime: 4.73, sessionStyle: 4.29, clarity: 4.84 },
  },
  {
    id: 2,
    name: 'Diego Alvarez',
    initials: 'DA',
    title: 'DevOps · Docker · Kubernetes',
    rating: 5.0,
    reviewCount: 4,
    hourlyRate: 80,
    available: true,
    skills: ['Docker', 'Kubernetes', 'AWS'],
    nextAvailable: [
      { time: '02:00 PM', available: true },
      { time: '04:00 PM', available: true },
      { time: '09:00 AM', available: true },
    ],
    location: 'Remote · Worldwide',
    language: 'English (Native)',
    responseTime: 'Responds within 3h',
    bio: 'Platform engineer specializing in container orchestration and CI/CD pipelines at scale.',
    aiSummary:
      'Diego is praised for deep infra knowledge and patient debugging sessions. Learners value real-world Kubernetes examples.',
    scores: { responseTime: 4.6, sessionStyle: 4.5, clarity: 4.7 },
  },
  {
    id: 3,
    name: 'Raj Patel',
    initials: 'RP',
    title: 'Node.js & backend architect',
    rating: 4.8,
    reviewCount: 92,
    hourlyRate: 75,
    available: true,
    skills: ['Node.js', 'PostgreSQL', 'System design'],
    nextAvailable: [
      { time: '02:00 PM', available: true },
      { time: '04:00 PM', available: true },
      { time: '09:00 AM', available: true },
    ],
    location: 'Remote · Worldwide',
    language: 'English, Hindi',
    responseTime: 'Responds within 1h',
    bio: 'Backend architect with a decade of experience designing scalable Node.js systems.',
    aiSummary:
      'Raj is highly rated for system design walkthroughs and structured, whiteboard-style sessions.',
    scores: { responseTime: 4.9, sessionStyle: 4.8, clarity: 4.75 },
  },
  {
    id: 4,
    name: 'Sam Ito',
    initials: 'SI',
    title: 'SQL & analytics engineer',
    rating: 4.8,
    reviewCount: 55,
    hourlyRate: 65,
    available: true,
    skills: ['SQL', 'PostgreSQL', 'dbt'],
    nextAvailable: [
      { time: '02:00 PM', available: true },
      { time: '04:00 PM', available: true },
      { time: '09:00 AM', available: true },
    ],
    location: 'Remote · Worldwide',
    language: 'English, Japanese',
    responseTime: 'Responds within 2h',
    bio: 'Analytics engineer focused on dbt modeling, warehouse design, and query performance.',
    aiSummary: 'Sam is praised for clean explanations of dbt models and SQL optimization.',
    scores: { responseTime: 4.65, sessionStyle: 4.7, clarity: 4.8 },
  },
  {
    id: 5,
    name: 'Lin Wei',
    initials: 'LW',
    title: 'Python & data engineering',
    rating: 4.7,
    reviewCount: 64,
    hourlyRate: 55,
    available: true,
    skills: ['Python', 'SQL', 'FastAPI'],
    nextAvailable: [
      { time: '02:00 PM', available: true },
      { time: '04:00 PM', available: true },
      { time: '09:00 AM', available: true },
    ],
    location: 'Remote · Worldwide',
    language: 'English, Mandarin',
    responseTime: 'Responds within 4h',
    bio: 'Data engineer building ETL pipelines and FastAPI services for ML teams.',
    aiSummary: 'Lin is valued for patient, methodical teaching of data pipeline design.',
    scores: { responseTime: 4.4, sessionStyle: 4.6, clarity: 4.65 },
  },
  {
    id: 6,
    name: 'Nora Hassan',
    initials: 'NH',
    title: 'MongoDB & full-stack JS',
    rating: 4.6,
    reviewCount: 40,
    hourlyRate: 50,
    available: true,
    skills: ['MongoDB', 'Node.js', 'React'],
    nextAvailable: [
      { time: '02:00 PM', available: true },
      { time: '04:00 PM', available: true },
      { time: '09:00 AM', available: true },
    ],
    location: 'Remote · Worldwide',
    language: 'English, Arabic',
    responseTime: 'Responds within 3h',
    bio: 'Full-stack JS developer specializing in MERN apps and schema design.',
    aiSummary: 'Nora is praised for approachable, beginner-friendly full-stack guidance.',
    scores: { responseTime: 4.5, sessionStyle: 4.55, clarity: 4.6 },
  },
]

export const mockReviews: Record<number, Review[]> = {
  1: [
    {
      id: 'r1',
      name: 'Priya Nair',
      initials: 'PN',
      date: '8/2/2026',
      rating: 5,
      comment: 'Ava explained hooks so clearly, finally clicked for me after weeks of confusion.',
      upvotes: 4,
      downvotes: 0,
      reply: {
        authorName: 'Ava Chen',
        authorInitials: 'AC',
        verified: true,
        date: '8/2/2026',
        comment: 'So glad it clicked! Feel free to book again once you start on Suspense.',
      },
    },
    {
      id: 'r2',
      name: 'Tom Baxter',
      initials: 'TB',
      date: '8/1/2026',
      rating: 4,
      comment: 'Great session but ran a bit over time, had to jump to my next call.',
      upvotes: 1,
      downvotes: 0,
      reply: {
        authorName: 'Ava Chen',
        authorInitials: 'AC',
        verified: true,
        date: '8/1/2026',
        comment: 'Thanks for the honest feedback, Tom — will keep a closer eye on the clock next time.',
      },
    },
    {
      id: 'r3',
      name: 'John Doe',
      initials: 'JD',
      date: '7/30/2026',
      rating: 5,
      comment: 'Really patient with beginner questions, walked through the render cycle step by step.',
      upvotes: 2,
      downvotes: 0,
    },
    {
      id: 'r4',
      name: 'Sara Lin',
      initials: 'SL',
      date: '7/28/2026',
      rating: 5,
      comment: 'Good session overall, would book again.',
      upvotes: 0,
      downvotes: 0,
    },
    {
      id: 'r5',
      name: 'Marcus Webb',
      initials: 'MW',
      date: '7/25/2026',
      rating: 4,
      comment: 'Solid explanation of context vs props drilling, nice diagrams on the whiteboard.',
      upvotes: 1,
      downvotes: 0,
    },
  ],
}

// Available days in the displayed month (dot indicator under the date)
export const availableDays = [4, 5, 6, 7, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 24, 25, 26, 27, 28, 31]

// Slots per day — vary by day so the picker feels real; falls back to a default set.
export const slotsByDay: Record<number, { time: string; period: 'Morning' | 'Afternoon' | 'Evening' }[]> = {
  10: [
    { time: '09:00 AM', period: 'Morning' },
    { time: '10:00 AM', period: 'Morning' },
  ],
}

export const defaultSlots: { time: string; period: 'Morning' | 'Afternoon' | 'Evening' }[] = [
  { time: '09:00 AM', period: 'Morning' },
  { time: '10:00 AM', period: 'Morning' },
  { time: '02:00 PM', period: 'Afternoon' },
  { time: '04:00 PM', period: 'Afternoon' },
]
